BookStore/Areas/Admin/Controllers/CoverTypeController.cs
using BookStore.DataAccess.Repository.IRepository;
using BookStore.Models;
using Microsoft.AspNetCore.Mvc;

namespace BookStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CoverTypeController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public CoverTypeController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public IActionResult Index()
        {
            IEnumerable<CoverType> coverTypes = _unitOfWork.CoverType.GetAll();
            return View(coverTypes);
        }
        //GET
        public IActionResult Create()
        {
            return View();
        }
        //POST
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Add(obj);
                _unitOfWork.Save();
                TempData["Success"] = "CoverType Created Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null || id == 0)
                return NotFound();
            var category = _unitOfWork.CoverType.GetFirstOrDefault(item => item.Id == id);
            if (category == null)
                return NotFound();

            return View(category);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CoverType obj)
        {
            if (ModelState.IsValid)
            {
                _unitOfWork.CoverType.Update(obj);
                _unitOfWork.Save();
                TempData["Success"] = "CoverType Updated Successfully";
                return RedirectToAction("Index");
            }
            return View(obj);
        }

        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
                return NotFound();
            var category = _unitOfWork.CoverType.GetFirstOrDefault(c => c.Id == id);
            if (category == null)
                return NotFound();

            return View(category);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var category = _unitOfWork.CoverType.GetFirstOrDefault(item => item.Id == id);
            if (category == null)
                return NotFound();

            _unitOfWork.CoverType.Remove(category);
            _unitOfWork.Save();
            TempData["Success"] = "CoverType Deleted Successfully";
            return RedirectToAction("Index");


        }

    }
}

BookStore/Areas/Admin/Views/CoverType/Create.cshtml
@model CoverType

<form method="post">
    <div class="border p-3 mt-4">
        <h2 class="text-primary">Create New Cover Type</h2>
    
    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
     
    
    <button type="submit" class="btn btn-primary" style="width:150px">Create</button>
    <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">Back</a>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
     }
}

BookStore/Areas/Admin/Views/CoverType/Delete.cshtml
@model CoverType

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-4">
        <h2 class="text-primary">Delete Cover Type</h2>
    
    <div class="mb-3">
        <label asp-for="Name" ></label>
        <input asp-for="Name" disabled class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
     
    
    <button type="submit" class="btn btn-danger" style="width:150px">Delete</button>
    <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">Back</a>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
     }
}

BookStore/Areas/Admin/Views/CoverType/Edit.cshtml
@model CoverType

<form method="post" asp-action="Edit">
    <div class="border p-3 mt-4">
        <h2 class="text-primary">Create New CoverType</h2>
    
    <div class="mb-3">
        <label asp-for="Name"></label>
        <input asp-for="Name" class="form-control" />
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    
    
    <button type="submit" class="btn btn-primary" style="width:150px">Update</button>
    <a asp-controller="CoverType" asp-action="Index" class="btn btn-secondary" style="width:150px">Back</a>
    </div>
</form>


@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
     }
}

BookStore/Areas/Admin/Views/CoverType/Index.cshtml
@model IEnumerable<CoverType>
@{
    ViewData["Title"] = "Index";
}
<div class="container p-3">
    <div class="row pt-3">
        <div class="col-6">
            <h2 class="text-primary">Cover Type List</h2>
        </div>
        <div class="col-6 text-end">
            <a asp-controller="CoverType" asp-action="Create" class="btn btn-primary" >
                <i class="bi bi-plus-circle-fill"></i> &nbsp; New Cover Type</a>
        </div>
    </div>
</div>
<br />
<table class="table table-bordered table-striped" style="width:100%" >
    <thead>
        <tr>
            <th>
              Cover Type Name
            </th>            
            <th>
                Edit
            </th>
            <th>
                Delete
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach(var obj in Model)
        {<tr>
            <th width=20%>
              @obj.Name
            </th>
           
            <th width=20%>
                <div class="w-75 btn-group" role="group">
                    <a asp-controller="CoverType" asp-action="Edit" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                        <i class="bi bi-pencil-square"></i>Edit</a>
                </div>
            </th>
            <th width=20%>
                <div class="w-75 btn-group" role="group">
                    <a asp-controller="CoverType" asp-action="Delete" asp-route-id="@obj.Id" class="btn btn-primary mx-2">
                        <i class="bi bi-trash3"></i>Delete</a>
                </div>
            </th>
        </tr>
        }
    </tbody>
</table>